---
swagger: '2.0'
info:
  version: 1.0.0
  title: School Wind Project Locations
  description: Access locations of installed and planned school wind energy projects
    in the United States for K-12, community colleges, universities, and other education
    centers.
paths:
  "/schoolprojects/{id}":
    get:
      responses:
        '200':
          description: Request was successful
          schema:
            "$ref": "#/definitions/schoolproject"
      description: ''
      tags:
      - schoolprojects.json
      summary: Find a model instance by id from the data source
      operationId: findById
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: path
        description: Model id
        name: id
        required: true
        type: string
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/schoolprojects":
    get:
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              "$ref": "#/definitions/schoolproject"
      description: ''
      tags:
      - schoolprojects.json
      summary: Find all instances of the model matched by filter from the data source
      operationId: find
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: query
        description: Filter defining fields, where, orderBy, offset, and limit
        name: filter
        required: false
        type: string
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/schoolprojects/findOne":
    get:
      responses:
        '200':
          description: Request was successful
          schema:
            "$ref": "#/definitions/schoolproject"
      description: ''
      tags:
      - schoolprojects.json
      summary: Find first instance of the model matched by filter from the data source
      operationId: findOne
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: query
        description: Filter defining fields, where, orderBy, offset, and limit
        name: filter
        required: false
        type: string
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
  "/schoolprojects/count":
    get:
      responses:
        '200':
          description: Request was successful
          schema:
            type: number
      description: ''
      tags:
      - schoolprojects.json
      summary: Count instances of the model matched by where from the data source
      operationId: count
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: query
        description: Criteria to match model instances
        name: where
        required: false
        type: string
      - in: query
        description: API Key
        name: api_key
        required: true
        type: string
        default: DEMO_KEY
basePath: "/api/windexchange"
tags:
- name: schoolprojects.json
schemes:
- https
definitions:
  schoolproject:
    properties:
      additionalresources:
        maxLength: 1000
        type: string
      address:
        maxLength: 100
        type: string
      city:
        maxLength: 50
        type: string
      commissiondate:
        type: string
        format: date
      contactemailaddress:
        maxLength: 100
        type: string
      contactfax:
        maxLength: 50
        type: string
      contactname:
        maxLength: 255
        type: string
      contactphone:
        maxLength: 50
        type: string
      countryid:
        maxLength: 2
        type: string
      countryname:
        maxLength: 100
        type: string
      developer:
        maxLength: 100
        type: string
      discussion:
        type: string
      educationalprograms:
        type: boolean
      host:
        maxLength: 100
        type: string
      id:
        type: number
        format: double
      lastupdated:
        type: string
        format: date
      latitude:
        type: number
        format: double
      longitude:
        type: number
        format: double
      mapidentificationnew:
        type: number
        format: double
      mapidentificationold:
        type: number
        format: double
      markertype:
        maxLength: 15
        type: string
      newf:
        type: boolean
      owneroperator:
        maxLength: 100
        type: string
      photo1:
        maxLength: 100
        type: string
      photo1alt:
        maxLength: 300
        type: string
      photo1caption:
        maxLength: 300
        type: string
      photo1height:
        maxLength: 4
        type: string
      photo1link:
        maxLength: 100
        type: string
      photo1width:
        maxLength: 4
        type: string
      photo2:
        maxLength: 100
        type: string
      photo2alt:
        maxLength: 300
        type: string
      photo2caption:
        maxLength: 300
        type: string
      photo2height:
        maxLength: 4
        type: string
      photo2link:
        maxLength: 100
        type: string
      photo2width:
        maxLength: 4
        type: string
      postalcode:
        maxLength: 10
        type: string
      projectname:
        maxLength: 100
        type: string
      projectnameurl:
        maxLength: 255
        type: string
      projecttype:
        maxLength: 50
        type: string
      province:
        maxLength: 50
        type: string
      schools:
        type: boolean
      stateid:
        maxLength: 2
        type: string
      status:
        maxLength: 50
        type: string
      statusdisplay:
        maxLength: 50
        type: string
      technologydescription:
        maxLength: 255
        type: string
      totalsize:
        type: number
        format: double
      totalsizeold:
        maxLength: 50
        type: string
      wacid:
        type: number
        format: double
      wfstype:
        maxLength: 50
        type: string
      windappcenter:
        maxLength: 100
        type: string
      windappcenterurl:
        maxLength: 255
        type: string
    required:
    - id
    - statusdisplay
