swagger: "2.0"
info:
  version: "1.0.0"
  title: Lab APIs
  description: |-
    A collection of APIs providing data about national laboratories related to associated with the Department of Energy's (DOE) Lab Partnering Service (LPS).
schemes:
  - https
basePath: /api/lps/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
  - api_key: []
paths:
  /labs:
    get:
      summary: Returns a list of national laboratories
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/labs_response"
  /labs/{lab_uuid}:
    get:
      summary: Returns detailed information about a national laboratory
      parameters:
      - in: path
        name: lab_uuid
        type: string
        required: true
        description: UUID of the national laboratory to get
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/lab_response"
definitions:
  lab_response:
    type: object
    $ref: "../definitions/lab.yml#/lab_response"
  labs_response:
    type: object
    $ref: "../definitions/lab.yml#/labs_response"