swagger: "2.0"
info:
  version: "1.0.0"
  title: Lab APIs
  description: |-
    A collection of APIs providing data about national laboratories related to associated with the Department of Energy's (DOE) Lab Partnering Service (LPS).
schemes:
  - https
basePath: /api/lps/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
  - api_key: []
paths:
  /labs:
    get:
      summary: Returns a list of national laboratories
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/labs_response"
  /labs/{lab_uuid}:
    get:
      summary: Returns detailed information about a national laboratory
      parameters:
      - in: path
        name: lab_uuid
        type: string
        required: true
        description: UUID of the national laboratory to get
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/lab_response"
definitions:
  metadata:
    type: object
    properties:
      version:
        type: string
        example: 1.0
  errors:
    type: array
    items:
      type: string
  lab:
    type: object
    properties:
      uuid:
        type: string
        example: 243e2911-3e43-40ba-b08b-418b21d23d38
      name:
        type: string
        example: Ames Laboratory
      tto_url:
        type: string
        example: http://www.techtransfer.iastate.edu/
      contact_us_email:
        type: string
        example: contactus@iastate.edu
      avatar:
        type: string
        example: developer.nrel.gov/labs/41665339-db90-4067-8f1a-e93567208f39/avatar_uuid
      links:
        type: object
        properties:
          self:
            type: string
            example: developer.nrel.gov/api/v1/labs/41665339-db90-4067-8f1a-e93567208f39
      alias:
        type: string
        example: ames
      description:
        type: string
        example: Ames Laboratory, a U.S. Department of Energy Office of Science National Laboratory managed by Iowa State University, creates materials and energy solutions. With its roots in the Manhattan Project, Ames Laboratory today seeks solutions to energy-related problems of national importance through the
      contact_email:
        type: string
        example: ameslps@ameslab.gov
      contact_name:
        type: string
        example: Beth Pieper
      location:
        type: string
        example: Ames, Iowa
      experts:
        type: array
        items:
          properties:
            uuid:
              type: string
              example: fb5af872-beb8-4323-acb4-d072c512561d
            first_name:
              type: string
              example: Iver
            last_name:
              type: string
              example: Anderson
            avatar:
              type: string
              example: https://www.labpartnering.org/experts/fb5af872-beb8-4323-acb4-d072c512561d/avatar
            links:
              type: object
              properties:
                self:
                  type: string
                  example: https://developer.nrel.gov/api/lps/v1/experts/fb5af872-beb8-4323-acb4-d072c512561d
    required:
    - uuid
    - name
    - alias
  laboratories:
    type: array
    items:
      $ref: "#/definitions/lab"
  labs_response:
    type: object
    properties:
      metadata:
        type: object
        $ref: "#/definitions/metadata"
      errors:
        type: object
        $ref: "#/definitions/errors"
      resultset:
        type: object
        $ref: "#/definitions/laboratories"
  lab_response:
    type: object
    properties:
      metadata:
        type: object
        $ref: "#/definitions/metadata"
      errors:
        type: object
        $ref: "#/definitions/errors"
      resultset:
        type: object
        $ref: "#/definitions/lab"
#  lab_response:
#    type: object
#    $ref: "../definitions/lab.yml#/lab_response"
#  labs_response:
#    type: object
#    $ref: "../definitions/lab.yml#/labs_response"