swagger: "2.0"
info:
  version: "1.0.0"
  title: Expert APIs
  description: |-
    A collection of APIs providing data about national laboratorty experts related to associated with the Department of Energy's (DOE) Lab Partnering Service (LPS).
schemes:
  - https
basePath: /api/lps/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
  - api_key: []
paths:
  /experts:
    get:
      summary: Returns a list of national laboratory experts
      parameters:
      - in: query
        name: lab_alias
        type: string
        enum:
          - ames
          - anl
          - bnl
          - fnal
          - inl
          - kcnsc
          - lanl
          - lbnl
          - llnl
          - netl
          - nrel
          - ornl
          - pantex
          - pnnl
          - pppl
          - slac
          - snl
          - srnl
          - tjnaf
          - y12

        required: false
        description: National laboratory alias, when not specified all experts are returnd from all labs
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/experts_response"
  /experts/{expert_uuid}:
    get:
      summary: Returns detailed information about a national laboratory expert
      parameters:
      - in: path
        name: expert_uuid
        schema:
          type: string
        required: true
        description: UUID of the national laboratory expert to get
      responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/expert_response"
definitions:
  expert_response:
    type: object
    $ref: "../definitions/expert.yml#/expert_response"
  experts_response:
    type: object
    $ref: "../definitions/expert.yml#/experts_response"