swagger: "2.0"
info:
  title: C-LEAP Electricity and Natural Gas APIs
  description: |-
    A collection of APIs providing data related to electricty and natural gas markets, including energy usage and expenditures, and GHG emissions.

    These APIs return derived data for places, which are queried via ZIP codes, city/state or gisjoin parameters.

    - Data is rounded to give approximations due to derived status.
    - There is no index dump of all data, a city/state or zip must be included if not querying a gisjoin.
    - Obtain gisjoin IDs via the [`/api/cleap/v1/cities`](/docs/cleap/general/) API.
schemes:
  - https
basePath: /api/cleap/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
paths:
  /energy_expenditures_and_ghg_by_sector:
    get:
      summary: Get the energy expenditures and ghg by sector data for a zip or city/state.
      parameters:
        - name: api_key
          in: query
          type: string
          description: Required. Get an API key from https://developer.nrel.gov/signup/.
        - name: city
          in: query
          type: string
          description: Required, along with `state_abbr`, unless `zip` is specified.
        - name: state_abbr
          in: query
          type: string
          description: Required, along with `city`, unless `zip` is specified.
        - name: zip
          in: query
          type: string
          description: Required, unless `city` and `state_abbr` are specified.
      responses:
        "200":
          schema:
            $ref: "#/definitions/energy_expenditures_and_ghg_by_sector"

  /energy_expenditures_and_ghg_by_sector/{gisjoin}:
    get:
      summary: Get the energy expenditures and ghg by sector data for the specific gisjoin.
      parameters:
        - name: api_key
          in: query
          type: string
          description: Required. Get an API key from https://developer.nrel.gov/signup/.
        - name: gisjoin
          in: path
          type: string
          description: Required. Query the [`/api/cleap/v1/cities`](/docs/cleap/general/) API for this value.
      responses:
        "200":
          schema:
            $ref: "#/definitions/energy_expenditures_and_ghg_by_sector"

  /electricity_and_gas_stats:
    get:
      summary: Get the electricity and gas statistics by sector.
      parameters:
        - name: api_key
          in: query
          type: string
          description: Required. Get an API key from https://developer.nrel.gov/signup/.
      responses:
        "200":
          schema:
            $ref: "#/definitions/electricity_and_gas_stats"
definitions:
  energy_expenditures_and_ghg_by_sector:
    properties:
      residential:
        type: object
        properties:
          housing_units:
            type: number
            example: 283600
            description: residential housing units
          total_pop:
            type: number
            example: 590500
            description: total residential population
          elec_1kdollars:
            type: number
            example: 327800
            description: residential electric 1k dollars
          elec_mwh:
            type: number
            example: 2901900
            description: residential electric megawatt hours
          gas_1kdollars:
            type: number
            example: 208100
            description: residential gas 1k dollars
          gas_mcf:
            type: number
            example: 26861300
            description: residential gas mcf
          elec_1kdollars_bin_min:
            type: number
            example: 26861300
            description: residential elec 1k dollars bin min
          elec_1kdollars_bin_max:
            type: number
            example: 26861300
            description: residential elec 1k dollars bin max
          elec_mwh_bin_min:
            type: number
            example: 26861300
            description: residential elec mwh bin min
          elec_mwh_bin_max:
            type: number
            example: 26861300
            description: residential elec mwh bin max
          gas_1kdollars_bin_min:
            type: number
            example: 26861300
            description: residential gas 1k dollars bin min
          gas_1kdollars_bin_max:
            type: number
            example: 26861300
            description: residential gas 1k dollars bin max
          gas_mcf_bin_min:
            type: number
            example: 26861300
            description: residential gas mcf bin min
          gas_mcf_bin_max:
            type: number
            example: 26861300
            description: residential gas mcf bin min
          elec_lb_ghg:
            type: number
            example: 5315074600
            description: residential elec lb ghg
          elec_min_lb_ghg:
            type: number
            example: 4372700300
            description: residential elec min lb ghg
          elec_max_lb_ghg:
            type: number
            example: 5465783800
            description: residential elec max lb ghg
          gas_lb_ghg:
            type: number
            example: 3224505500
            description: residential gas lb ghg
          gas_min_lb_ghg:
            type: number
            example: 3124075000
            description: residential gas min lb ghg
          gas_max_lb_ghg: 3364388500
      commercial:
        type: object
        properties:
          housing_units:
            type: number
            example: 283600
            description: commercial housing units
          total_pop:
            type: number
            example: 590500
            description: total commercial population
          elec_1kdollars:
            type: number
            example: 327800
            description: commercial electric 1k dollars
          elec_mwh:
            type: number
            example: 2901900
            description: commercial electric megawatt hours
          gas_1kdollars:
            type: number
            example: 208100
            description: commercial gas 1k dollars
          gas_mcf:
            type: number
            example: 26861300
            description: commercial gas mcf
          elec_1kdollars_bin_min:
            type: number
            example: 26861300
            description: commercial elec 1k dollars bin min
          elec_1kdollars_bin_max:
            type: number
            example: 26861300
            description: commercial elec 1k dollars bin max
          elec_mwh_bin_min:
            type: number
            example: 26861300
            description: commercial elec mwh bin min
          elec_mwh_bin_max:
            type: number
            example: 26861300
            description: commercial elec mwh bin max
          gas_1kdollars_bin_min:
            type: number
            example: 26861300
            description: commercial gas 1k dollars bin min
          gas_1kdollars_bin_max:
            type: number
            example: 26861300
            description: commercial gas 1k dollars bin max
          gas_mcf_bin_min:
            type: number
            example: 26861300
            description: commercial gas mcf bin min
          gas_mcf_bin_max:
            type: number
            example: 26861300
            description: commercial gas mcf bin min
          elec_lb_ghg:
            type: number
            example: 5315074600
            description: commercial elec lb ghg
          elec_min_lb_ghg:
            type: number
            example: 4372700300
            description: commercial elec min lb ghg
          elec_max_lb_ghg:
            type: number
            example: 5465783800
            description: commercial elec max lb ghg
          gas_lb_ghg:
            type: number
            example: 3224505500
            description: commercial gas lb ghg
          gas_min_lb_ghg:
            type: number
            example: 3124075000
            description: commercial gas min lb ghg
          gas_max_lb_ghg: 3364388500
      industrial:
        type: object
        properties:
          housing_units:
            type: number
            example: 283600
            description: industrial housing units
          total_pop:
            type: number
            example: 590500
            description: total industrial population
          elec_1kdollars:
            type: number
            example: 327800
            description: industrial electric 1k dollars
          elec_mwh:
            type: number
            example: 2901900
            description: industrial electric megawatt hours
          gas_1kdollars:
            type: number
            example: 208100
            description: industrial gas 1k dollars
          gas_mcf:
            type: number
            example: 26861300
            description: industrial gas mcf
          elec_1kdollars_bin_min:
            type: number
            example: 26861300
            description: industrial elec 1k dollars bin min
          elec_1kdollars_bin_max:
            type: number
            example: 26861300
            description: industrial elec 1k dollars bin max
          elec_mwh_bin_min:
            type: number
            example: 26861300
            description: industrial elec mwh bin min
          elec_mwh_bin_max:
            type: number
            example: 26861300
            description: industrial elec mwh bin max
          gas_1kdollars_bin_min:
            type: number
            example: 26861300
            description: industrial gas 1k dollars bin min
          gas_1kdollars_bin_max:
            type: number
            example: 26861300
            description: industrial gas 1k dollars bin max
          gas_mcf_bin_min:
            type: number
            example: 26861300
            description: industrial gas mcf bin min
          gas_mcf_bin_max:
            type: number
            example: 26861300
            description: industrial gas mcf bin min
          elec_lb_ghg:
            type: number
            example: 5315074600
            description: industrial elec lb ghg
          elec_min_lb_ghg:
            type: number
            example: 4372700300
            description: industrial elec min lb ghg
          elec_max_lb_ghg:
            type: number
            example: 5465783800
            description: industrial elec max lb ghg
          gas_lb_ghg:
            type: number
            example: 3224505500
            description: industrial gas lb ghg
          gas_min_lb_ghg:
            type: number
            example: 3124075000
            description: industrial gas min lb ghg
          gas_max_lb_ghg: 3364388500
  electricity_and_gas_stats:
    properties:
      commercial:
        type: object
        properties:
          elec_mwh_per_city:
            type: number
            example: 45387.256
            description: elec mwh per city
          elec_1kdollars_per_city:
            type: number
            example: 4107.144
            description: elec 1k dollars per city
          elec_mwh_per_capita:
            type: number
            example: 4.628
            description: elec mwh per capita
          elec_1kdollars_per_capita:
            type: number
            example: 0.419
            description: elec 1k dollars per capita
          elec_mwh_per_establishment:
            type: number
            example: 176.632
            description: elec mwh per establishment
          elec_1kdollars_per_establishment:
            type: number
            example: 15.984
            description: elec 1k dollars per establishment
          gas_mcf_per_city:
            type: number
            example: 151639.007
            description: gas mcf per city
          gas_1kdollars_per_city:
            type: number
            example: 833.822
            description: gas 1k dollars per city
          gas_mcf_per_capita:
            type: number
            example: 12.126
            description: gas mcf per capita
          gas_1kdollars_per_capita:
            type: number
            example: 0.067
            description: gas 1k dollars per capita
          gas_mcf_per_establishment:
            type: number
            example: 462.829
            description: gas mcf per establishment
          gas_1kdollars_per_establishment:
            type: number
            example: 2.545
            description: gas 1k dollars per establishment
      residential:
        type: object
        properties:
          elec_mwh_per_city:
            type: number
            example: 45387.256
            description: elec mwh per city
          elec_1kdollars_per_city:
            type: number
            example: 4107.144
            description: elec 1k dollars per city
          elec_mwh_per_capita:
            type: number
            example: 4.628
            description: elec mwh per capita
          elec_1kdollars_per_capita:
            type: number
            example: 0.419
            description: elec 1k dollars per capita
          elec_mwh_per_housing_unit:
            type: number
            example: 176.632
            description: elec mwh per housing unit
          elec_1kdollars_per_housing_unit:
            type: number
            example: 15.984
            description: elec 1k dollars per housing unit
          gas_mcf_per_city:
            type: number
            example: 151639.007
            description: gas mcf per city
          gas_1kdollars_per_city:
            type: number
            example: 833.822
            description: gas 1k dollars per city
          gas_mcf_per_capita:
            type: number
            example: 12.126
            description: gas mcf per capita
          gas_1kdollars_per_capita:
            type: number
            example: 0.067
            description: gas 1k dollars per capita
          gas_mcf_per_housing_unit:
            type: number
            example: 462.829
            description: gas mcf per housing unit
          gas_1kdollars_per_housing_unit:
            type: number
            example: 2.545
            description: gas 1k dollars per housing unit
      industrial:
        type: object
        properties:
          elec_mwh_per_city:
            type: number
            example: 45387.256
            description: elec mwh per city
          elec_1kdollars_per_city:
            type: number
            example: 4107.144
            description: elec 1k dollars per city
          elec_mwh_per_capita:
            type: number
            example: 4.628
            description: elec mwh per capita
          elec_1kdollars_per_capita:
            type: number
            example: 0.419
            description: elec 1k dollars per capita
          elec_mwh_per_establishment:
            type: number
            example: 176.632
            description: elec mwh per establishment
          elec_1kdollars_per_establishment:
            type: number
            example: 15.984
            description: elec 1k dollars per establishment
          gas_mcf_per_city:
            type: number
            example: 151639.007
            description: gas mcf per city
          gas_1kdollars_per_city:
            type: number
            example: 833.822
            description: gas 1k dollars per city
          gas_mcf_per_capita:
            type: number
            example: 12.126
            description: gas mcf per capita
          gas_1kdollars_per_capita:
            type: number
            example: 0.067
            description: gas 1k dollars per capita
          gas_mcf_per_establishment:
            type: number
            example: 462.829
            description: gas mcf per establishment
          gas_1kdollars_per_establishment:
            type: number
            example: 2.545
            description: gas 1k dollars per establishment
