swagger: "2.0"
info:
  version: "1.0.0"
  title: EVI-Pro API
  description: |-
    APIs providing output from NREL's EVI-Pro model.

    - hello world
    - words
    - words
schemes:
  - https
basePath: /api/evi-pro/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
  - api_key: []
paths:
  /load_profile:
    get:
      summary: Get the load profile
      parameters:
        - name: temp_c
          in: query
          type: string
          enum: [-20, -10, 0, 10, 20, 30, 40]
          required: true
          description: Degrees in Celsius for the day on which load profile shape is desired.  Must be one of `[-20, -10, 0, 10, 20, 30, 40]`.
        - name: fleet_size
          in: query
          type: string
          required: true
          enum: [1000, 10000, 50000]
          description: Fleet size.  Must be one of `[1000, 10000, 50000]`.
        - name: mean_dvmt
          in: query
          type: string
          required: true
          enum: [25, 35, 45]
          description: Average fleet daily vehicle miles traveled.  Must be one of `[25, 35, 45]`.
        - name: pev_dist
          in: query
          type: string
          required: true
          enum: [BEV, PHEV, EQUAL]
          description: PEV distribution where numbers correlate to % of vehicle type `PHEV20, PHEV50, BEV100, BEV250`.  Must be one of `[BEV, PHEV, EQUAL]` where `BEV` represents BEV dominant scenario (10/15/25/50), `PHEV` represents PHEV dominant (25/50/10/15), and `EQUAL` represents PHEV/BEV equal shares (15/35/15/35).
        - name: class_dist
          in: query
          type: string
          required: true
          enum: [SEDAN, SUV, EQUAL]
          description: Vehicle class distribution.  Must be one of `[X, SUV, X]` where `SEDAN` is sedan dominant scenario (80/20), `SUV` is SUV dominant (20/80), and `EQUAL` represents equal distribution (50/50).
        - name: pref_dist
          in: query
          type: string
          required: true
          enum: [HOME60, HOME80, HOME100]
          description: Preference for charging at home (versus at work).  Must be one of `[HOME60, HOME80, HOME100]` where 60% perfer home charging, 80% prefer home charging, and 100% prefer home charging.
        - name: home_access_dist
          in: query
          type: string
          required: true
          enum: [HA50, HA75, HA100]
          description: Access to home power where numbers represent access to home power.  Must be one of `[HA50, HA75, HA100]` where `HA100` reflects a region with a high fraction of single family homes.
        - name: home_power_dist
          in: query
          type: string
          required: true
          enum: [MostL1, MostL2, ???]
          description: Options for home power distribution scenarios where `MostL1` represents 80% L1 charging, 20% L2, `MostL2` represents 20% L1 charging, 80% L2, and `EvenL2` represents 50% L1 charging, 50% L2.  Must be one of `[MostL1, MostL2, ?]`
        - name: work_power_dist
          in: query
          type: string
          required: true
          enum: [MostL1, MostL2, ???]
          description: Options for work power distribution scenarios where `MostL1` represents 80% L1 charging, 20% L2, `MostL2` represents 20% L1 charging, 80% L2, and `EvenL2` represents 50% L1 charging, 50% L2.  Must be one of `[MostL1, MostL2, ?]`
      responses:
        "200":
          description: Successful request
          schema:
            $ref: "#/definitions/load_profile"
definitions:
  error:
    type: object
    properties:
      code:
        type: string
        description: A static code value representing the type of error.
        example: NOT_FOUND
      developer_message:
        type: string
        description: A human readable description of the error message.
        example: No data was found for the gisjoin provided
  load_profile:
    properties:
      errors:
        type: array
        items:
          $ref: "#/definitions/error"
        example: []
      inputs:
        type: object
        properties:
          temp_c:
            type: string
            example: -20
          fleet_size:
            type: string
            example: 1000
          mean_dvmt:
            type: string
            example: 45
          pev_dist:
            type: string
            example: PHEV
          class_dist:
            type: string
            example: SUV
          pref_dist:
            type: string
            example: Home60
          home_access_dist:
            type: string
            example: HA50
          home_power_dist:
            type: string
            example: MostL2
          work_power_dist:
            type: string
            example: MostL2
          day_of_week:
            type: string
            example: foo
          pev_type:
            type: string
            example: foo
          class_type:
            type: string
            example: foo
          dest_type:
            type: string
            example: foo
          dest_chg_level:
            type: string
            example: foo
          type:
            type: string
            example: residential
          state_abbr:
            type: string
            example: ny
      metadata:
        type: object
        properties:
          version:
            type: string
            example: 1.0.0
      result:
        type: array
        items:
          properties:
            series_id:
              type: string
              example: EMISS.CO2-TOTV-IC-TO-CO.A
            name:
              type: string
              example: "Industrial carbon dioxide emissions, all fuels, Colorado"
            units:
              type: string
              example: million metric tons CO2
            f:
              type: string
              example: A
            unitsshort:
              type: string
              example: mmt CO2
            description:
              type: string
              example: See http://www.eia.gov/environment/emissions/state/analysis/ for technical notes and documentation.
            copyright:
              type: string
              example: None
            source:
              type: string
              example: "EIA, U.S. Energy Information Administration"
            iso3166:
              type: string
              example: USA-CO
            geography:
              type: string
              example: USA-CO
            start:
              type: number
              example: 1980
            end:
              type: number
              example: 2014
            updated:
              type: string
              example: 2017-01-26T14:27:58-0500
            data:
              type: object
              properties:
                "1980":
                  type: number
                  example: 10.516286
                "1981":
                  type: number
                  example: 8.392009
                "1982":
                  type: number
                  example: 7.190044
                "1983":
                  type: number
                  example: 6.452622
                "1984":
                  type: number
                  example: 6.244769
                "1985":
                  type: number
                  example: 5.313541
                "1986":
                  type: number
                  example: 5.570528
                "1987":
                  type: number
                  example: 5.095779
                "1988":
                  type: number
                  example: 5.85142
                "1989":
                  type: number
                  example: 6.421156
                "1990":
                  type: number
                  example: 6.509537
                "1991":
                  type: number
                  example: 7.509993
                "1992":
                  type: number
                  example: 7.699262
                "1993":
                  type: number
                  example: 8.419759
                "1994":
                  type: number
                  example: 7.84506
                "1995":
                  type: number
                  example: 7.758708
                "1996":
                  type: number
                  example: 7.990315
                "1997":
                  type: number
                  example: 8.328755
                "1998":
                  type: number
                  example: 8.872571
                "1999":
                  type: number
                  example: 8.518556
                "2000":
                  type: number
                  example: 9.3555
                "2001":
                  type: number
                  example: 12.872679
                "2002":
                  type: number
                  example: 12.176083
                "2003":
                  type: number
                  example: 11.939549
                "2004":
                  type: number
                  example: 12.643321
                "2005":
                  type: number
                  example: 13.562539
                "2006":
                  type: number
                  example: 13.616127
                "2007":
                  type: number
                  example: 13.597258
                "2008":
                  type: number
                  example: 13.984433
                "2009":
                  type: number
                  example: 13.619995
                "2010":
                  type: number
                  example: 14.634091
                "2011":
                  type: number
                  example: 13.193981
                "2012":
                  type: number
                  example: 13.412163
                "2013":
                  type: number
                  example: 13.486865
                "2014":
                  type: number
                  example: 14.237501