swagger: "2.0"
info:
  version: "1.0.0"
  title: Emissions APIs
  description: |-
    A collection of APIs providing data related to GHG emissions.

    These endpoints return derived data for places, which are queried via state_abbr and type.

    - Data is rounded to give approximations due to derived status.
    - There is no index dump of all data.  A `state_abbr` and `type` must be provided.
    - All APIs require the `api_key` parameter. Get an API key from https://developer.nrel.gov/signup/.
schemes:
  - https
basePath: /api/cleap/v1
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
security:
  - api_key: []
paths:
  /state_co2_emissions:
    get:
      summary: Get CO2 emissions by state and type.
      parameters:
        - name: state_abbr
          in: query
          type: string
          required: true
          description: Required, along with `type`.
        - name: type
          in: query
          type: string
          required: true
          description: Required, along with `state_abbr`.  Choices are `'commercial', 'electric', 'residential', 'industrial', 'transportation', 'total'`.
      responses:
        "200":
          description: Successful request
          schema:
            $ref: "#/definitions/state_co2_emissions"
definitions:
  error:
    type: object
    properties:
      code:
        type: string
        description: A static code value representing the type of error.
        example: NOT_FOUND
      developer_message:
        type: string
        description: A human readable description of the error message.
        example: No data was found for the gisjoin provided
  state_co2_emissions:
    properties:
      errors:
        type: array
        items:
          $ref: "#/definitions/error"
        example: []
      inputs:
        type: object
        properties:
          type:
            type: string
            example: residential
          state_abbr:
            type: string
            example: ny
      metadata:
        type: object
        properties:
          version:
            type: string
            example: 1.0.0
      result:
        type: array
        items:
          properties:
            series_id:
              type: string
              example: EMISS.CO2-TOTV-IC-TO-CO.A
            name:
              type: string
              example: "Industrial carbon dioxide emissions, all fuels, Colorado"
            units:
              type: string
              example: million metric tons CO2
            f:
              type: string
              example: A
            unitsshort:
              type: string
              example: mmt CO2
            description:
              type: string
              example: See http://www.eia.gov/environment/emissions/state/analysis/ for technical notes and documentation.
            copyright:
              type: string
              example: None
            source:
              type: string
              example: "EIA, U.S. Energy Information Administration"
            iso3166:
              type: string
              example: USA-CO
            geography:
              type: string
              example: USA-CO
            start:
              type: string
              example: "1980"
            end:
              type: string
              example: "2014"
            updated:
              type: string
              example: 2017-01-26T14:27:58-0500
            data:
              type: object
              properties:
                "1980":
                  type: number
                  example: 10.516286